### ISSUE TITLE
Set the DAI-Lab username and e-mail address as defaults in the cookiecutter.json

### ISSUE THREAD

**Issue by csala** [DAI-Lab/cookiecutter-pypackage#17]
Most of the DAI-Lab projects, if not all of them, should be using the DAI-Lab username and address:
* author: `MIT Data To AI Lab`
* author_email: `dailabmit@gmail.com`

Right now the cookiecutter prompt asks for the user Name and E-mail Address, so most of the times cookiecutter users end up using their own name there, which later on need to be corrected.

**Comment by micahjsmith** [comment]
Closed by 09d9ed1
