### ISSUE TITLE
Add D3-AI in the list of possible github_orgnames

### ISSUE THREAD

**Issue by csala** [DAI-Lab/cookiecutter-pypackage#18]
Right now only "HDI-Project", "DAI-Lab" or the user's own GitHub Username are listed as available options.

**Comment by micahjsmith** [comment]
For other special cases, can overwrite the options: https://cookiecutter.readthedocs.io/en/latest/advanced/choice_variables.html?highlight=extra%20context%20choice#overwriting-default-choice-values

Example, create `./custom.yaml`
```
default_context:
    github_orgname: "foo"
```
And invoke with `cookiecutter --config-file ./custom.yaml gh:DAI-Lab/cookiecutter-pypackage`
