### ISSUE TITLE
Allow Circle to be used instead of Travis

### ISSUE THREAD

**Issue by micahjsmith** [DAI-Lab/cookiecutter-pypackage#2]
Some people seem to prefer it. Modify the cookiecutter to create either a .travis.yml or a .circleci/config.yml file based on the person's preference.

**Comment by csala** [comment]
An interesting note about CircleCI: even though most people ends up using a custom config.yml, one nice feature of CircleCI is that if configuration is not found in the repo it infers how to test the package.

And it does a good job at it!

For example, if tox.ini is found, it ends up running something like:
```
pyton setup.py install
python setup.py test
tox
```
which is probably is just what you would end up doing in a default config.yml.

So, if circleci is to be used, my suggestion is to simply add nothing to the repository.

**Comment by micahjsmith** [comment]
interesting!

do you know if its possible to configure Circle to deploy to PyPI and GitHub Pages? I imagine if so, a custom .circle/config.yml would be needed.

**Comment by csala** [comment]
CircleCI has been discarded to avoid confusions between the two systems, so this issue can be closed.
