### ISSUE TITLE
The bumpversion pre-release serialization format is not semver compliant

### ISSUE THREAD

**Issue by micahjsmith** [DAI-Lab/cookiecutter-pypackage#43]
Pre-release versions are serialized like: `0.2.1.dev0`. This is not a valid version number according to <semver.org>:

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>
```

Pre-releases should be separated from the core version number with a hyphen only, a dot is not valid.

**Comment by micahjsmith** [comment]
@csala

**Comment by micahjsmith** [comment]
anyway it turns out that semver and [PEP 440](https://www.python.org/dev/peps/pep-0440/) are incompatible on this point

**Comment by csala** [comment]
Shall we close the issue?
