### ISSUE TITLE
Improve bumpversion configuration

### ISSUE THREAD

**Issue by csala** [DAI-Lab/cookiecutter-pypackage#6]
Bumpversion configuration should be adapted to allow using development (`-dev`) versions.

**Comment by micahjsmith** [comment]
@csala Can you please update the CONTRIBUTING.rst with the workflow you have created? You can consider creating a makefile target or an expanding an existing target if there are a lot of steps that are done repeatedly.

**Comment by micahjsmith** [comment]
Closed by #15
