### ISSUE TITLE
Update setup.py/requirements with new scheme

### ISSUE THREAD

**Issue by micahjsmith** [DAI-Lab/cookiecutter-pypackage#7]
I think we have the following situation
- setup.py has dev and test sections under extras_require
- no requirements*.txt files are needed
- installation is done via `pip install foo`, testing is done via `pip install foo[test] && python -m pytest`, and development is done via `pip install foo[dev]` 

@csala can expand on this discussion :) 

We should also make very clear the recommended way to install in 
- makefile
- README

And the recommended way to develop in
- makefile
- CONTRIBUTING

**Comment by micahjsmith** [comment]
Also requires updating the README of this cookiecutter template to have updated instructions on installing package for development

**Comment by csala** [comment]
I totally agree on this.

And indeed, I have a PR half prepared that includes this change.
